Draft PR of multibranch conditionals
pvdrz/pijama_legacy pull request #74
Opened 2020-05-22 02:40 UTC by seanchen1991

2020-05-22 03:59 UTC, christianpoveda commented on src/ast/visitor.rs
> +        let if_blk = &branch.cond;
Could you add a `visit_branch` and `super_branch` methods to the trait? I think that'd be easier to maintain.

2020-05-22 03:59 UTC, christianpoveda commented on src/ast/mod.rs
> +pub struct Branch<'a> {
I know we don't have a lot of docs but could you add an small description of this structure?

2020-05-22 04:45 UTC, christianpoveda commented on src/ast/visitor.rs
> +        // let if_blk = &if_branch.cond;
Clean these when you're done 

(I usually forget to do that kind of stuff)

2020-05-22 05:23 UTC, pvdrz requested changes

2020-05-22 05:23 UTC, christianpoveda commented on src/parser/node/cond.rs
> +            many0(pair(elif_block, do_block)),
remove this line for now

2020-05-22 05:23 UTC, christianpoveda commented on src/parser/node/cond.rs
> +        move |(sp1, if_block, do_block, elif_block, else_block, sp2)| {
same here, remove the new `elif_block`

2020-05-22 05:23 UTC, christianpoveda commented on tests/parse/mod.rs
> +// #[test]
Also remove the commented test (but plz save it somewhere else, there is no way anyone is going to rewrite that huge AST :P)

2020-05-22 05:23 UTC, christianpoveda commented on tests/parse/elif.pj
> +if x do y elif a do b else z end
same for this file. But save it somewhere else

2020-05-23 02:12 UTC, pvdrz requested changes

2020-05-23 02:12 UTC, christianpoveda commented on src/parser/node/cond.rs
> +//! cond = "if" block1 "do" block1 ("elif" block1 "do" block1) ("else" block1)? "end"
change `("elif" block1 "do" block1)` to  `("elif" block1 "do" block1)*` to indicate that there could be zero or more of those.

Also change the `("else" block1)?` by just `"else" block1`. That used to be the grammar when we had optional `else`s but we no longer do that and I forgot to update the docs :/

2020-05-23 02:12 UTC, christianpoveda commented on src/parser/node/cond.rs
> +// pub fn cond(input: Span) -> IResult<Located<Node>> {
remove this dead code

2020-05-23 02:12 UTC, christianpoveda commented on src/parser/node/cond.rs
> +//! Thus, `elif` and `else` blocks are optional and are represented as empty [`Block`]s inside the
plz remove the "and `else`". That's a leftover of some changes I did and forgot to update the docs :/

2020-05-23 05:08 UTC, pvdrz approved these changes

2020-05-23 05:08 UTC, merged